In [1]:
import tensorflow as tf
tf.test.is_gpu_available()
gpu = tf.config.list_physical_devices('GPU')
print(gpu)
print("dfs")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
dfs


In [2]:
tf.test.is_gpu_available()

True

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.2942707 , -0.18384771, -0.3771805 ,  0.20037931,  0.28927758,
         0.76308507,  0.36226222,  0.4401873 ,  0.15450339,  0.19674692]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.10375045, 0.06431997, 0.05301301, 0.09445251, 0.1032337 ,
        0.16580342, 0.11104994, 0.12004961, 0.09021731, 0.09411003]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [8]:
loss_fn(y_train[:1], predictions).numpy()


1.7969524

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [16]:
model.fit(x_train, y_train, epochs=10)


Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0248 - accuracy: 0.9913
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0246 - accuracy: 0.9913
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0252 - accuracy: 0.9911
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0229 - accuracy: 0.9921
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0220 - accuracy: 0.9928
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0223 - accuracy: 0.9925
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0204 - accuracy: 0.9930
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0202 - accuracy: 0.9933
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0189 - accuracy: 0.9937
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.020

In [17]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.1011 - accuracy: 0.9799


[0.10113608092069626, 0.9799000024795532]

In [18]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [19]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.5907305e-19, 7.4435409e-15, 7.4429514e-13, 4.5390294e-07,
        5.1799491e-20, 4.3087795e-15, 7.5288203e-28, 9.9999952e-01,
        3.3423215e-13, 1.9310549e-09],
       [3.7799811e-16, 1.6965463e-12, 1.0000000e+00, 1.2046340e-16,
        0.0000000e+00, 1.2426978e-16, 5.9665371e-16, 1.6872257e-32,
        1.5744404e-14, 0.0000000e+00],
       [8.9731370e-14, 9.9998665e-01, 6.5648862e-07, 4.9156054e-11,
        5.2821612e-11, 9.0081678e-11, 4.3705653e-10, 1.6198344e-07,
        1.2559560e-05, 1.1785509e-15],
       [9.9999988e-01, 2.8827913e-20, 6.7606116e-08, 6.0133300e-13,
        2.0648143e-15, 2.8250864e-09, 2.9798011e-10, 1.4784308e-12,
        8.0310884e-16, 9.5894572e-14],
       [1.4318240e-10, 4.6222782e-20, 7.0425610e-11, 7.7267431e-16,
        9.9994540e-01, 6.5027996e-12, 7.9934665e-13, 2.3727281e-07,
        6.6578942e-13, 5.4350272e-05]], dtype=float32)>

In [20]:
tf.__version__

'2.6.0'